### PR TITLE
Enhanced User Recognition: Fetch User by ID

### PR DESCRIPTION
**Pull request by ThatsLiamS**
I hope this message finds you well. I am writing to submit a pull request for the open source Discord bot in response to Issue #2, which addresses the limitation mentioned regarding the bot's responsiveness only to user tags.

I have made modifications to the helper.js file within the helper directory. The primary change involves updating the `getUserFromMention` to `fetchUserId` function to support both Discord mentions and user IDs. Here's the modified code snippet:

```javascript
function fetchUserId(string) {
    if (!string) return false;

    /* Is it a valid mention? */
    const mentionMatches = string.match(/^<@!?(\d+)>$/);
    if (mentionMatches && mentionMatches[1]) {
        return mentionMatches[1];
    }

    /* Non-Valid Mentions: Assume ID Provided */
    const idMatches = string.match(/^\d{18}$/);
    if (idMatches && idMatches[0]) {
        return idMatches[0];
    }

    /* ID has not been found */
    return false;
}
```
Additionally, I have updated all the relevant files that call this command to handle the case where the function returns false. In such instances, the bot will now send a default embed indicating that a valid user wasn't provided.
I believe this enhancement will improve the bot's usability in various scenarios.

Please review the changes at your earliest convenience. I am open to any feedback and will promptly address any concerns or suggestions you may have.

Thank you for your time and consideration.

Best regards,

### CODE REVIEW

**Comment by dvbuka** [comment]
Hi Liam!

Thanks for the PR. I really like your approach to the user ID filtering so I'll definitely be adding it in. I should've made it more explicit that search by name meant that users of the bot also assign first names to themselves that is stored in the MongoDB collection, but I do think having searching by @\tags and Discord IDs will be helpful anyways. I'll add another set of checks for the ProfileSchema.name case as well.

There's API changes between discord.js v13 and v14 that make your PR and the existing code incompatible (ex: MessageEmbed vs EmbedBuilder), so I'll be working on changing everything to v14 in the coming days before I merge into main.

Best,
Dasha

**Comment by ThatsLiamS** [comment]
Hi Dasha,

Thank you for your positive feedback! I'm glad you appreciate the approac. 

I apologise for the oversight regarding DiscordJS versions. I'll make sure to address that promptly. If you'd like, I can have the compatible DiscordJS code pushed within the next couple of hours. Let me know how you'd prefer to proceed? 

Thanks,  Liam

**Comment by dvbuka** [comment]
If you'd like to, go ahead! I won't be able to work on this project for a few more days, but it looks like v13 is still being maintained and we can just change EmbedBuilder back to MessageEmbed.

**Comment by ThatsLiamS** [comment]
Please find the agreed-upon changes listed above. Please review the changes at your earliest convenience. I am open to any feedback and will promptly address any concerns or suggestions you may have.

**Comment by dvbuka** [comment]
Everything looks great, so I've merged into main. Thank you for your help!

**Pull request merged**
